/**
 *
 *  Mock_SmartrepoTestOrders.cc
 *  Hand-maintained mock of a Drogon ORM model for unit tests.
 *  NOT generated by drogon_ctl — safe from setup_tests.sh overwrite.
 *
 */

#include "Mock_SmartrepoTestOrders.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::smartrepo_test;

const std::string Mock_SmartrepoTestOrders::Cols::_id = "\"id\"";
const std::string Mock_SmartrepoTestOrders::Cols::_user_id = "\"user_id\"";
const std::string Mock_SmartrepoTestOrders::Cols::_amount = "\"amount\"";
const std::string Mock_SmartrepoTestOrders::Cols::_discount = "\"discount\"";
const std::string Mock_SmartrepoTestOrders::Cols::_is_express = "\"is_express\"";
const std::string Mock_SmartrepoTestOrders::Cols::_priority = "\"priority\"";
const std::string Mock_SmartrepoTestOrders::Cols::_status = "\"status\"";
const std::string Mock_SmartrepoTestOrders::Cols::_label = "\"label\"";
const std::string Mock_SmartrepoTestOrders::Cols::_metadata = "\"metadata\"";
const std::string Mock_SmartrepoTestOrders::Cols::_created_at = "\"created_at\"";
const std::string Mock_SmartrepoTestOrders::Cols::_address = "\"address\"";
const std::string Mock_SmartrepoTestOrders::Cols::_history = "\"history\"";
const std::string Mock_SmartrepoTestOrders::Cols::_quantities = "\"quantities\"";
const std::string Mock_SmartrepoTestOrders::Cols::_tags = "\"tags\"";
const std::string Mock_SmartrepoTestOrders::primaryKeyName = "id";
const bool Mock_SmartrepoTestOrders::hasPrimaryKey = true;
const std::string Mock_SmartrepoTestOrders::tableName = "\"smartrepo_test_orders\"";

const std::vector<typename Mock_SmartrepoTestOrders::MetaData> Mock_SmartrepoTestOrders::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"user_id","int64_t","bigint",8,0,0,1},
{"amount","int32_t","integer",4,0,0,1},
{"discount","int32_t","integer",4,0,0,0},
{"is_express","bool","boolean",1,0,0,1},
{"priority","std::string","character varying",20,0,0,1},
{"status","std::string","character varying",20,0,0,1},
{"label","std::string","character varying",200,0,0,1},
{"metadata","std::string","text",0,0,0,1},
{"created_at","::trantor::Date","timestamp with time zone",0,0,0,1},
{"address","std::string","jsonb",0,0,0,0},
{"history","std::string","jsonb",0,0,0,0},
{"quantities","std::string","jsonb",0,0,0,0},
{"tags","std::string","jsonb",0,0,0,0}
};
const std::string &Mock_SmartrepoTestOrders::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Mock_SmartrepoTestOrders::Mock_SmartrepoTestOrders(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>(r["user_id"].as<int64_t>());
        }
        if(!r["amount"].isNull())
        {
            amount_=std::make_shared<int32_t>(r["amount"].as<int32_t>());
        }
        if(!r["discount"].isNull())
        {
            discount_=std::make_shared<int32_t>(r["discount"].as<int32_t>());
        }
        if(!r["is_express"].isNull())
        {
            isExpress_=std::make_shared<bool>(r["is_express"].as<bool>());
        }
        if(!r["priority"].isNull())
        {
            priority_=std::make_shared<std::string>(r["priority"].as<std::string>());
        }
        if(!r["label"].isNull())
        {
            label_=std::make_shared<std::string>(r["label"].as<std::string>());
        }
        if(!r["metadata"].isNull())
        {
            metadata_=std::make_shared<std::string>(r["metadata"].as<std::string>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 9 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            amount_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            discount_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            isExpress_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            priority_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            label_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            metadata_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

Mock_SmartrepoTestOrders::Mock_SmartrepoTestOrders(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            amount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            discount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            isExpress_=std::make_shared<bool>(pJson[pMasqueradingVector[4]].asBool());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            priority_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            label_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            metadata_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

Mock_SmartrepoTestOrders::Mock_SmartrepoTestOrders(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("amount"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["amount"].isNull())
        {
            amount_=std::make_shared<int32_t>((int32_t)pJson["amount"].asInt64());
        }
    }
    if(pJson.isMember("discount"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["discount"].isNull())
        {
            discount_=std::make_shared<int32_t>((int32_t)pJson["discount"].asInt64());
        }
    }
    if(pJson.isMember("is_express"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["is_express"].isNull())
        {
            isExpress_=std::make_shared<bool>(pJson["is_express"].asBool());
        }
    }
    if(pJson.isMember("priority"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["priority"].isNull())
        {
            priority_=std::make_shared<std::string>(pJson["priority"].asString());
        }
    }
    if(pJson.isMember("label"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["label"].isNull())
        {
            label_=std::make_shared<std::string>(pJson["label"].asString());
        }
    }
    if(pJson.isMember("metadata"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["metadata"].isNull())
        {
            metadata_=std::make_shared<std::string>(pJson["metadata"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Mock_SmartrepoTestOrders::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            amount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            discount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            isExpress_=std::make_shared<bool>(pJson[pMasqueradingVector[4]].asBool());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            priority_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            label_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            metadata_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Mock_SmartrepoTestOrders::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("amount"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["amount"].isNull())
        {
            amount_=std::make_shared<int32_t>((int32_t)pJson["amount"].asInt64());
        }
    }
    if(pJson.isMember("discount"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["discount"].isNull())
        {
            discount_=std::make_shared<int32_t>((int32_t)pJson["discount"].asInt64());
        }
    }
    if(pJson.isMember("is_express"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["is_express"].isNull())
        {
            isExpress_=std::make_shared<bool>(pJson["is_express"].asBool());
        }
    }
    if(pJson.isMember("priority"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["priority"].isNull())
        {
            priority_=std::make_shared<std::string>(pJson["priority"].asString());
        }
    }
    if(pJson.isMember("label"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["label"].isNull())
        {
            label_=std::make_shared<std::string>(pJson["label"].asString());
        }
    }
    if(pJson.isMember("metadata"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["metadata"].isNull())
        {
            metadata_=std::make_shared<std::string>(pJson["metadata"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int64_t &Mock_SmartrepoTestOrders::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Mock_SmartrepoTestOrders::getId() const noexcept
{
    return id_;
}
void Mock_SmartrepoTestOrders::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Mock_SmartrepoTestOrders::PrimaryKeyType & Mock_SmartrepoTestOrders::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &Mock_SmartrepoTestOrders::getValueOfUserId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Mock_SmartrepoTestOrders::getUserId() const noexcept
{
    return userId_;
}
void Mock_SmartrepoTestOrders::setUserId(const int64_t &pUserId) noexcept
{
    userId_ = std::make_shared<int64_t>(pUserId);
    dirtyFlag_[1] = true;
}

const int32_t &Mock_SmartrepoTestOrders::getValueOfAmount() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(amount_)
        return *amount_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Mock_SmartrepoTestOrders::getAmount() const noexcept
{
    return amount_;
}
void Mock_SmartrepoTestOrders::setAmount(const int32_t &pAmount) noexcept
{
    amount_ = std::make_shared<int32_t>(pAmount);
    dirtyFlag_[2] = true;
}

const int32_t &Mock_SmartrepoTestOrders::getValueOfDiscount() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(discount_)
        return *discount_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Mock_SmartrepoTestOrders::getDiscount() const noexcept
{
    return discount_;
}
void Mock_SmartrepoTestOrders::setDiscount(const int32_t &pDiscount) noexcept
{
    discount_ = std::make_shared<int32_t>(pDiscount);
    dirtyFlag_[3] = true;
}
void Mock_SmartrepoTestOrders::setDiscountToNull() noexcept
{
    discount_.reset();
    dirtyFlag_[3] = true;
}

const bool &Mock_SmartrepoTestOrders::getValueOfIsExpress() const noexcept
{
    static const bool defaultValue = bool();
    if(isExpress_)
        return *isExpress_;
    return defaultValue;
}
const std::shared_ptr<bool> &Mock_SmartrepoTestOrders::getIsExpress() const noexcept
{
    return isExpress_;
}
void Mock_SmartrepoTestOrders::setIsExpress(const bool &pIsExpress) noexcept
{
    isExpress_ = std::make_shared<bool>(pIsExpress);
    dirtyFlag_[4] = true;
}

const std::string &Mock_SmartrepoTestOrders::getValueOfPriority() const noexcept
{
    static const std::string defaultValue = std::string();
    if(priority_)
        return *priority_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Mock_SmartrepoTestOrders::getPriority() const noexcept
{
    return priority_;
}
void Mock_SmartrepoTestOrders::setPriority(const std::string &pPriority) noexcept
{
    priority_ = std::make_shared<std::string>(pPriority);
    dirtyFlag_[5] = true;
}
void Mock_SmartrepoTestOrders::setPriority(std::string &&pPriority) noexcept
{
    priority_ = std::make_shared<std::string>(std::move(pPriority));
    dirtyFlag_[5] = true;
}

const std::string &Mock_SmartrepoTestOrders::getValueOfStatus() const noexcept
{
    static const std::string defaultValue = std::string();
    if(status_)
        return *status_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Mock_SmartrepoTestOrders::getStatus() const noexcept
{
    return status_;
}
void Mock_SmartrepoTestOrders::setStatus(const std::string &pStatus) noexcept
{
    status_ = std::make_shared<std::string>(pStatus);
    dirtyFlag_[13] = true;
}
void Mock_SmartrepoTestOrders::setStatus(std::string &&pStatus) noexcept
{
    status_ = std::make_shared<std::string>(std::move(pStatus));
    dirtyFlag_[13] = true;
}

const std::string &Mock_SmartrepoTestOrders::getValueOfLabel() const noexcept
{
    static const std::string defaultValue = std::string();
    if(label_)
        return *label_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Mock_SmartrepoTestOrders::getLabel() const noexcept
{
    return label_;
}
void Mock_SmartrepoTestOrders::setLabel(const std::string &pLabel) noexcept
{
    label_ = std::make_shared<std::string>(pLabel);
    dirtyFlag_[6] = true;
}
void Mock_SmartrepoTestOrders::setLabel(std::string &&pLabel) noexcept
{
    label_ = std::make_shared<std::string>(std::move(pLabel));
    dirtyFlag_[6] = true;
}

const std::string &Mock_SmartrepoTestOrders::getValueOfMetadata() const noexcept
{
    static const std::string defaultValue = std::string();
    if(metadata_)
        return *metadata_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Mock_SmartrepoTestOrders::getMetadata() const noexcept
{
    return metadata_;
}
void Mock_SmartrepoTestOrders::setMetadata(const std::string &pMetadata) noexcept
{
    metadata_ = std::make_shared<std::string>(pMetadata);
    dirtyFlag_[7] = true;
}
void Mock_SmartrepoTestOrders::setMetadata(std::string &&pMetadata) noexcept
{
    metadata_ = std::make_shared<std::string>(std::move(pMetadata));
    dirtyFlag_[7] = true;
}

const ::trantor::Date &Mock_SmartrepoTestOrders::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Mock_SmartrepoTestOrders::getCreatedAt() const noexcept
{
    return createdAt_;
}
void Mock_SmartrepoTestOrders::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[8] = true;
}

const std::string &Mock_SmartrepoTestOrders::getValueOfAddress() const noexcept
{
    static const std::string defaultValue = std::string();
    if(address_)
        return *address_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Mock_SmartrepoTestOrders::getAddress() const noexcept
{
    return address_;
}
void Mock_SmartrepoTestOrders::setAddress(const std::string &pAddress) noexcept
{
    address_ = std::make_shared<std::string>(pAddress);
    dirtyFlag_[9] = true;
}
void Mock_SmartrepoTestOrders::setAddress(std::string &&pAddress) noexcept
{
    address_ = std::make_shared<std::string>(std::move(pAddress));
    dirtyFlag_[9] = true;
}

const std::string &Mock_SmartrepoTestOrders::getValueOfHistory() const noexcept
{
    static const std::string defaultValue = std::string();
    if(history_)
        return *history_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Mock_SmartrepoTestOrders::getHistory() const noexcept
{
    return history_;
}
void Mock_SmartrepoTestOrders::setHistory(const std::string &pHistory) noexcept
{
    history_ = std::make_shared<std::string>(pHistory);
    dirtyFlag_[10] = true;
}
void Mock_SmartrepoTestOrders::setHistory(std::string &&pHistory) noexcept
{
    history_ = std::make_shared<std::string>(std::move(pHistory));
    dirtyFlag_[10] = true;
}

const std::string &Mock_SmartrepoTestOrders::getValueOfQuantities() const noexcept
{
    static const std::string defaultValue = std::string();
    if(quantities_)
        return *quantities_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Mock_SmartrepoTestOrders::getQuantities() const noexcept
{
    return quantities_;
}
void Mock_SmartrepoTestOrders::setQuantities(const std::string &pQuantities) noexcept
{
    quantities_ = std::make_shared<std::string>(pQuantities);
    dirtyFlag_[11] = true;
}
void Mock_SmartrepoTestOrders::setQuantities(std::string &&pQuantities) noexcept
{
    quantities_ = std::make_shared<std::string>(std::move(pQuantities));
    dirtyFlag_[11] = true;
}

const std::string &Mock_SmartrepoTestOrders::getValueOfTags() const noexcept
{
    static const std::string defaultValue = std::string();
    if(tags_)
        return *tags_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Mock_SmartrepoTestOrders::getTags() const noexcept
{
    return tags_;
}
void Mock_SmartrepoTestOrders::setTags(const std::string &pTags) noexcept
{
    tags_ = std::make_shared<std::string>(pTags);
    dirtyFlag_[12] = true;
}
void Mock_SmartrepoTestOrders::setTags(std::string &&pTags) noexcept
{
    tags_ = std::make_shared<std::string>(std::move(pTags));
    dirtyFlag_[12] = true;
}

void Mock_SmartrepoTestOrders::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Mock_SmartrepoTestOrders::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "user_id",
        "amount",
        "discount",
        "is_express",
        "priority",
        "label",
        "metadata",
        "created_at"
    };
    return inCols;
}

void Mock_SmartrepoTestOrders::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getAmount())
        {
            binder << getValueOfAmount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDiscount())
        {
            binder << getValueOfDiscount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getIsExpress())
        {
            binder << getValueOfIsExpress();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getPriority())
        {
            binder << getValueOfPriority();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getLabel())
        {
            binder << getValueOfLabel();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getMetadata())
        {
            binder << getValueOfMetadata();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Mock_SmartrepoTestOrders::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    return ret;
}

void Mock_SmartrepoTestOrders::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getAmount())
        {
            binder << getValueOfAmount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDiscount())
        {
            binder << getValueOfDiscount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getIsExpress())
        {
            binder << getValueOfIsExpress();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getPriority())
        {
            binder << getValueOfPriority();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getLabel())
        {
            binder << getValueOfLabel();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getMetadata())
        {
            binder << getValueOfMetadata();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Mock_SmartrepoTestOrders::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=(Json::Int64)getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getAmount())
    {
        ret["amount"]=getValueOfAmount();
    }
    else
    {
        ret["amount"]=Json::Value();
    }
    if(getDiscount())
    {
        ret["discount"]=getValueOfDiscount();
    }
    else
    {
        ret["discount"]=Json::Value();
    }
    if(getIsExpress())
    {
        ret["is_express"]=getValueOfIsExpress();
    }
    else
    {
        ret["is_express"]=Json::Value();
    }
    if(getPriority())
    {
        ret["priority"]=getValueOfPriority();
    }
    else
    {
        ret["priority"]=Json::Value();
    }
    if(getLabel())
    {
        ret["label"]=getValueOfLabel();
    }
    else
    {
        ret["label"]=Json::Value();
    }
    if(getMetadata())
    {
        ret["metadata"]=getValueOfMetadata();
    }
    else
    {
        ret["metadata"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

std::string Mock_SmartrepoTestOrders::toString() const
{
    return toJson().toStyledString();
}

Json::Value Mock_SmartrepoTestOrders::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 9)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getAmount())
            {
                ret[pMasqueradingVector[2]]=getValueOfAmount();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getDiscount())
            {
                ret[pMasqueradingVector[3]]=getValueOfDiscount();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getIsExpress())
            {
                ret[pMasqueradingVector[4]]=getValueOfIsExpress();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getPriority())
            {
                ret[pMasqueradingVector[5]]=getValueOfPriority();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getLabel())
            {
                ret[pMasqueradingVector[6]]=getValueOfLabel();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getMetadata())
            {
                ret[pMasqueradingVector[7]]=getValueOfMetadata();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[8]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=(Json::Int64)getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getAmount())
    {
        ret["amount"]=getValueOfAmount();
    }
    else
    {
        ret["amount"]=Json::Value();
    }
    if(getDiscount())
    {
        ret["discount"]=getValueOfDiscount();
    }
    else
    {
        ret["discount"]=Json::Value();
    }
    if(getIsExpress())
    {
        ret["is_express"]=getValueOfIsExpress();
    }
    else
    {
        ret["is_express"]=Json::Value();
    }
    if(getPriority())
    {
        ret["priority"]=getValueOfPriority();
    }
    else
    {
        ret["priority"]=Json::Value();
    }
    if(getLabel())
    {
        ret["label"]=getValueOfLabel();
    }
    else
    {
        ret["label"]=Json::Value();
    }
    if(getMetadata())
    {
        ret["metadata"]=getValueOfMetadata();
    }
    else
    {
        ret["metadata"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

bool Mock_SmartrepoTestOrders::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, true))
            return false;
    }
    else
    {
        err="The user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("amount"))
    {
        if(!validJsonOfField(2, "amount", pJson["amount"], err, true))
            return false;
    }
    else
    {
        err="The amount column cannot be null";
        return false;
    }
    if(pJson.isMember("discount"))
    {
        if(!validJsonOfField(3, "discount", pJson["discount"], err, true))
            return false;
    }
    if(pJson.isMember("is_express"))
    {
        if(!validJsonOfField(4, "is_express", pJson["is_express"], err, true))
            return false;
    }
    if(pJson.isMember("priority"))
    {
        if(!validJsonOfField(5, "priority", pJson["priority"], err, true))
            return false;
    }
    if(pJson.isMember("label"))
    {
        if(!validJsonOfField(6, "label", pJson["label"], err, true))
            return false;
    }
    if(pJson.isMember("metadata"))
    {
        if(!validJsonOfField(7, "metadata", pJson["metadata"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(8, "created_at", pJson["created_at"], err, true))
            return false;
    }
    return true;
}
bool Mock_SmartrepoTestOrders::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                             const std::vector<std::string> &pMasqueradingVector,
                                                             std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Mock_SmartrepoTestOrders::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("amount"))
    {
        if(!validJsonOfField(2, "amount", pJson["amount"], err, false))
            return false;
    }
    if(pJson.isMember("discount"))
    {
        if(!validJsonOfField(3, "discount", pJson["discount"], err, false))
            return false;
    }
    if(pJson.isMember("is_express"))
    {
        if(!validJsonOfField(4, "is_express", pJson["is_express"], err, false))
            return false;
    }
    if(pJson.isMember("priority"))
    {
        if(!validJsonOfField(5, "priority", pJson["priority"], err, false))
            return false;
    }
    if(pJson.isMember("label"))
    {
        if(!validJsonOfField(6, "label", pJson["label"], err, false))
            return false;
    }
    if(pJson.isMember("metadata"))
    {
        if(!validJsonOfField(7, "metadata", pJson["metadata"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(8, "created_at", pJson["created_at"], err, false))
            return false;
    }
    return true;
}
bool Mock_SmartrepoTestOrders::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                           const std::vector<std::string> &pMasqueradingVector,
                                                           std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Mock_SmartrepoTestOrders::validJsonOfField(size_t index,
                                           const std::string &fieldName,
                                           const Json::Value &pJson,
                                           std::string &err,
                                           bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 200)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 200)";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
