#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

#include <glaze/glaze.hpp>

namespace relais_test {

// Nested structs (plain C++ — auto-reflected by Glaze)

struct TestCoordinateMetadata {
    float accuracy = 0.0f;
    std::string source;
};

struct TestGeoLocation {
    double latitude = 0.0;
    double longitude = 0.0;
    TestCoordinateMetadata metadata;
};

struct TestAddress {
    std::string street;
    std::string city;
    std::string zip_code;
    TestGeoLocation geo;
};

// Priority enum — no glz::meta here, auto-generated by the wrapper generator

enum class Priority {
    Low = 0,
    Medium = 1,
    High = 2,
    Critical = 3
};

// Status enum — shared across applications, glz::meta defined here for BEVE compatibility

enum class Status {
    Pending = 0,
    Processing = 1,
    Shipped = 2,
    Delivered = 3
};

// @relais table=relais_test_orders
// @relais output=fixtures/generated/TestOrderWrapper.h
struct TestOrder {
    int64_t id = 0; // @relais primary_key db_managed
    int64_t user_id = 0;
    int32_t amount = 0;
    std::optional<int32_t> discount;
    bool is_express = false;
    Priority priority = Priority::Low; // @relais enum=low:Low,medium:Medium,high:High,critical:Critical
    Status status = Status::Pending; // @relais enum
    std::string label;
    glz::raw_json metadata;
    std::string created_at; // @relais timestamp db_managed
    TestAddress address; // @relais json_field
    std::vector<TestAddress> history; // @relais json_field
    std::vector<int32_t> quantities; // @relais json_field
    std::vector<std::string> tags; // @relais json_field
};

}  // namespace relais_test

// ============================================================================
// Glaze metadata for Status enum (shared — developer-defined)
// ============================================================================

template<>
struct glz::meta<relais_test::Status> {
    using enum relais_test::Status;
    static constexpr auto value = glz::enumerate(
        "pending", Pending,
        "processing", Processing,
        "shipped", Shipped,
        "delivered", Delivered
    );
};
