#pragma once

#include <cstdint>
#include <optional>
#include <string>

namespace relais_test {

// Slot state — no glz::meta here, auto-generated by the wrapper generator
enum class SlotState {
    Free = 0,
    Held = 1,
    Taken = 2
};

// One row per claimable resource: covers relative updates (counter, expires_at),
// guards on an enum, a nullable holder and a nullable timestamp, compare-and-set
// on version, and ordering on priority.
//
// @relais table=relais_test_slots
struct TestSlot {
    int64_t id = 0;                         // @relais primary_key db_managed
    int64_t group_id = 0;
    SlotState state = SlotState::Free;      // @relais enum=free:Free,held:Held,taken:Taken
    std::optional<int64_t> holder;
    std::optional<std::string> expires_at;  // @relais timestamp
    int32_t counter = 0;
    int64_t version = 0;
    int32_t priority = 0;
};

}  // namespace relais_test
