#pragma once

#include <cstdint>
#include <string>

namespace relais_test {

// Ticket state — no glz::meta here, auto-generated by the wrapper generator.
// Stored as text. The underlying values are deliberately out of step with both
// the declaration order and the alphabetical order of the database strings, so
// a test can tell which of the three orders a layer actually uses:
//   underlying    archived < open < closed < blocked
//   alphabetical  archived < blocked < closed < open
//   declaration   open < blocked < closed < archived
enum class TicketState {
    Open = 5,
    Blocked = 20,
    Closed = 10,
    Archived = 0
};

// Tickets paged by queue, filtered and sorted on a mapped enum. The `weight`
// filter sorts after the enum filters, so the encoded filter bytes that follow
// the enum must stay aligned for the Lua matcher.
//
// @relais table=relais_test_tickets
// @relais_list limits=10,50
struct TestTicket {
    int64_t id = 0;                         // @relais primary_key db_managed sortable:asc
    int64_t queue_id = 0;                   // @relais filterable:queue
    TicketState state = TicketState::Open;  // @relais enum=open:Open,blocked:Blocked,closed:Closed,archived:Archived filterable filterable:state_min:ge sortable:state:asc
    int32_t weight = 0;                     // @relais filterable
    std::string title;
};

}  // namespace relais_test
