#ifndef JCX_RELAIS_VERSION_H
#define JCX_RELAIS_VERSION_H

#define RELAIS_VERSION_MAJOR 3
#define RELAIS_VERSION_MINOR 0
#define RELAIS_VERSION_PATCH 0

// Single integer for comparisons: MAJOR*10000 + MINOR*100 + PATCH.
// 3.0.0 == 30000. Compare e.g. #if RELAIS_VERSION >= 30000.
#define RELAIS_VERSION \
    (RELAIS_VERSION_MAJOR * 10000 + RELAIS_VERSION_MINOR * 100 + RELAIS_VERSION_PATCH)

#endif  // JCX_RELAIS_VERSION_H
